# Generated by Selenium IDE

# To test:
# Firefox must be installed
# pip install selenium==4.30.0 pytest==8.3.5
# pytest -s test_study_helper.py

import pytest
import time
import pickle
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudyHelper():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.maximize_window()
    self.vars = {}
    self.URL = '3.17.39.162'
  
  def teardown_method(self, method):
    time.sleep(3)
    self.driver.quit()
  
  def test_signup(self):
    self.driver.get(f"http://{self.URL}/")
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("ExampleUser1")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("example@gmail.com")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("TestingSignUp123")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("TestingSignUp123")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert "home" in self.driver.current_url

  def test_login(self):
    self.driver.get(f"http://{self.URL}/")
    self.driver.find_element(By.ID, "loginUsername").click()
    self.driver.find_element(By.ID, "loginUsername").send_keys("ExampleUser1")
    self.driver.find_element(By.ID, "loginPassword").click()
    self.driver.find_element(By.ID, "loginPassword").send_keys("TestingSignUp123")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    cookies = self.driver.get_cookies()
    with open("cookies.pkl", "wb") as file:
      pickle.dump(cookies, file)
    assert "home" in self.driver.current_url

  def test_accessaccount(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    assert "account" in self.driver.current_url

  def test_addnote(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Notes").click()
    self.driver.find_element(By.LINK_TEXT, "+ New Note").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").clear()
    self.driver.find_element(By.ID, "id_title").send_keys("Math Test")
    self.driver.find_element(By.ID, "id_content").click()
    self.driver.find_element(By.ID, "id_content").send_keys("Study Calculus Formulas")
    time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

  def test_editnote(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Notes").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").clear()
    self.driver.find_element(By.ID, "id_title").send_keys("Math Test 2")
    self.driver.find_element(By.ID, "id_content").click()
    self.driver.find_element(By.ID, "id_content").clear()
    self.driver.find_element(By.ID, "id_content").send_keys("Study Calculus Formulas Study\nLinear Algebra Formulas")
    time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

  def test_searchnote(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Notes").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "+ New Note").click()
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").clear()
    self.driver.find_element(By.ID, "id_title").send_keys("Science Test")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "← Back to Notes").click()
    time.sleep(3)
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("Math Test")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary:nth-child(1)").click()

  def test_deletenote(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Notes").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()

  def test_addevent(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Calendar").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "btn-new-event").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "f-title").click()
    self.driver.find_element(By.ID, "f-title").send_keys("Math Exam")
    time.sleep(2)
    self.driver.find_element(By.ID, "f-start").click()
    self.driver.find_element(By.ID, "f-start").send_keys("04-24-2026T21:00")
    time.sleep(2)
    self.driver.find_element(By.ID, "f-tags").click()
    self.driver.find_element(By.ID, "f-tags").send_keys("Math")
    time.sleep(3)
    self.driver.find_element(By.ID, "btn-save").click()

  def test_editevent(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Calendar").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".event-pill").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "f-title").click()
    self.driver.find_element(By.ID, "f-title").clear()
    self.driver.find_element(By.ID, "f-title").send_keys("Math Exam 2")
    self.driver.find_element(By.ID, "f-desc").click()
    self.driver.find_element(By.ID, "f-desc").clear()
    self.driver.find_element(By.ID, "f-desc").send_keys("Algebra")
    time.sleep(2)
    self.driver.find_element(By.ID, "f-start").click()
    self.driver.find_element(By.ID, "f-start").clear()
    self.driver.find_element(By.ID, "f-start").send_keys("04-23-2026T22:00")
    self.driver.find_element(By.ID, "f-duration").click()
    self.driver.find_element(By.ID, "f-duration").clear()
    self.driver.find_element(By.ID, "f-duration").send_keys("90")
    time.sleep(2)
    self.driver.find_element(By.ID, "f-tags").click()
    self.driver.find_element(By.ID, "f-tags").clear()
    self.driver.find_element(By.ID, "f-tags").send_keys("Algebra")
    time.sleep(5)
    self.driver.find_element(By.ID, "btn-save").click()

  def test_deleteevent(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Calendar").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".event-pill").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "btn-delete").click()
    assert self.driver.switch_to.alert.text == "Delete this event?"
    time.sleep(3)
    self.driver.switch_to.alert.accept()

  def test_logout(self):
    self.driver.get(f"http://{self.URL}/home/")
    with open("cookies.pkl", "rb") as file:
      cookies = pickle.load(file)
    for cookie in cookies:
      self.driver.add_cookie(cookie)
    self.driver.refresh()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-light").click()
    time.sleep(3)
    assert self.driver.switch_to.alert.text == "Are you sure you want to log out?"
    self.driver.switch_to.alert.accept()
    assert "" in self.driver.current_url
